add kibana config file

diff --git a/install.yaml b/install.yaml
--- a/install.yaml
+++ b/install.yaml
@@ -4,6 +4,7 @@ pre_install_actions:
 
 project_files:
   - docker-compose.kibana.yaml
+  - ./kibana/config.yml
 
 dependencies:
   - elasticsearch
@@ -11,5 +12,16 @@ dependencies:
 global_files:
 
 post_install_actions:
-
+  - |
+    #ddev-no-display
+    if [ -f ./kibana/config.yml ] && ! grep '#ddev-generated' ./kibana/config.yml; then
+        echo "Existing ./kibana/config.yml does not have #ddev-generated, so can't be updated"
+        exit 2
+    fi
+    
+    baseUrl=${DDEV_PRIMARY_URL}
+    echo "Copy to ./kibana/config.yml server.publicBaseUrl: $baseUrl"
+    
+    sed -e "s/publicUrl/$baseUrl/g" ./kibana/config.yml
 yaml_read_files:
+
